### ISSUE TITLE
大佬您好，我在做

### ISSUE THREAD

**Issue by hosee16** [ethan-iai/LaVan-Pytorch#1]
我在运行您的文件的时候经常会遇到netClassifier.mean等等这种报错，类似于'Inception3' object has no attribute 'mean'等等，我有时候可以替换自己定义mean，但是太多这种错误了，不知道是不是自己弄错了，作者可以帮忙解答一下吗
可以有偿 谢谢！
sunboyang0716@163.com

**Comment by ethan-iai** [comment]
很抱歉现在才有时间答复。
问题由 PyTorch 版本过高导致，针对该问题以作修改。

**Comment by hosee16** [comment]
好的好的 谢谢大佬！麻烦了
